# Starter pipeline
- task: PowerShell@2
  inputs:
    filePath: '/scheduleCleanUp.ps1'
- task: AzurePowerShell@5
  inputs:
    ScriptType: 'FilePath'
    ScriptPath: '/scheduleCleanUp.ps1'
    azurePowerShellVersion: 'LatestVersion'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
